# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
platform :osx, '10.11'
use_frameworks!
inhibit_all_warnings!

target 'TinyPNG4Mac' do

pod 'Alamofire', '~> 4.8.2'
pod 'SwiftyJSON', '~> 5.0'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
  end
