# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
platform :osx, '10.12'
use_frameworks!
inhibit_all_warnings!

target 'TinyPNG4Mac' do

pod 'Alamofire', '~> 5.4.4'

end
